@extends('layouts.app')
@section('title')
    <title>Register</title>
@endsection
@section('content')
    <error-boundry>
        <register-component></register-component>
    </error-boundry>
@endsection
